version: '3.8'

services:
  backend:
    build:
      context: ./example-backend
    container_name: backend
    ports:
      - "8080:8080"
    restart: unless-stopped
    environment:
      - REQUEST_ORIGIN=http://localhost:5000
      - REDIS_HOST=redis
    depends_on:
      - redis

  frontend:
    build:
      context: ./example-frontend
      args:
        - REACT_APP_BACKEND_URL=http://localhost:8080
    container_name: frontend
    ports:
      - "5000:5000"
    depends_on:
      - backend

  redis:
    image: redis:7-alpine
    container_name: redis
    volumes:
      - redis_data:/data

volumes:
  redis_data:
