version: '3.8'

services:
  backend:
    build:
      context: ./example-backend
    container_name: backend
    ports:
      - "8080:8080"
    environment:
      - REQUEST_ORIGIN=http://frontend:5000

  frontend:
    build:
      context: ./example-frontend
    container_name: frontend
    ports:
      - "5000:5000"
    depends_on:
      - backend
