version: "3"

services:
  frontend:
    build:
      context: ./example-frontend
      args:
        REACT_APP_BACKEND_URL: /api
    depends_on:
      - backend

  backend:
    build:
      context: ./example-backend
    depends_on:
      - postgres
      - redis
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=example
      - POSTGRES_DB=appdb
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  postgres:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DB: appdb
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    restart: always

  nginx:
    image: nginx:alpine
    ports:
      - "80:80" 
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend

volumes:
  postgres_data:
